// Auto-generated by scripts/build-golf-sprite-sheet.mjs
export const GOLF_SPRITE_COLS = 6;
export const GOLF_SPRITE_ROWS = 6;
export const GOLF_SPRITE_ORDER = [
  "fairway",
  "green",
  "green__v2",
  "green__v3",
  "tee",
  "rough",
  "rough__v2",
  "sand",
  "sand__v2",
  "sand__v3",
  "water",
  "cart_path",
  "hole_flag",
  "golf_ball",
  "golfer_idle",
  "golfer_walk",
  "golfer_swing",
  "clubhouse_l1",
  "driving_range_l1",
  "maintenance_shed_l1",
  "practice_green_l1",
  "pro_shop_l1",
  "restaurant_l1",
  "clubhouse_l2",
  "driving_range_l2",
  "maintenance_shed_l2",
  "practice_green_l2",
  "pro_shop_l2",
  "restaurant_l2",
  "clubhouse_l3",
  "driving_range_l3",
  "maintenance_shed_l3",
  "practice_green_l3",
  "pro_shop_l3",
  "restaurant_l3"
] as const;
export const GOLF_SPRITE_BUILDINGS = {
  "fairway": {
    "row": 0,
    "col": 0
  },
  "green": {
    "row": 0,
    "col": 1
  },
  "green__v2": {
    "row": 0,
    "col": 2
  },
  "green__v3": {
    "row": 0,
    "col": 3
  },
  "tee": {
    "row": 0,
    "col": 4
  },
  "rough": {
    "row": 0,
    "col": 5
  },
  "rough__v2": {
    "row": 1,
    "col": 0
  },
  "sand": {
    "row": 1,
    "col": 1
  },
  "sand__v2": {
    "row": 1,
    "col": 2
  },
  "sand__v3": {
    "row": 1,
    "col": 3
  },
  "water": {
    "row": 1,
    "col": 4
  },
  "cart_path": {
    "row": 1,
    "col": 5
  },
  "hole_flag": {
    "row": 2,
    "col": 0
  },
  "golf_ball": {
    "row": 2,
    "col": 1
  },
  "golfer_idle": {
    "row": 2,
    "col": 2
  },
  "golfer_walk": {
    "row": 2,
    "col": 3
  },
  "golfer_swing": {
    "row": 2,
    "col": 4
  },
  "clubhouse_l1": {
    "row": 2,
    "col": 5
  },
  "driving_range_l1": {
    "row": 3,
    "col": 0
  },
  "maintenance_shed_l1": {
    "row": 3,
    "col": 1
  },
  "practice_green_l1": {
    "row": 3,
    "col": 2
  },
  "pro_shop_l1": {
    "row": 3,
    "col": 3
  },
  "restaurant_l1": {
    "row": 3,
    "col": 4
  },
  "clubhouse_l2": {
    "row": 3,
    "col": 5
  },
  "driving_range_l2": {
    "row": 4,
    "col": 0
  },
  "maintenance_shed_l2": {
    "row": 4,
    "col": 1
  },
  "practice_green_l2": {
    "row": 4,
    "col": 2
  },
  "pro_shop_l2": {
    "row": 4,
    "col": 3
  },
  "restaurant_l2": {
    "row": 4,
    "col": 4
  },
  "clubhouse_l3": {
    "row": 4,
    "col": 5
  },
  "driving_range_l3": {
    "row": 5,
    "col": 0
  },
  "maintenance_shed_l3": {
    "row": 5,
    "col": 1
  },
  "practice_green_l3": {
    "row": 5,
    "col": 2
  },
  "pro_shop_l3": {
    "row": 5,
    "col": 3
  },
  "restaurant_l3": {
    "row": 5,
    "col": 4
  }
} as const;
export const GOLF_SPRITE_VARIANTS = {
  "green": [
    "green",
    "green__v2",
    "green__v3"
  ],
  "rough": [
    "rough",
    "rough__v2"
  ],
  "sand": [
    "sand",
    "sand__v2",
    "sand__v3"
  ]
} as const;
